const CONFIG={whatsapp:"51999999999",email:"contacto@agp.com",locale:"es-PE",currency:"PEN"};
const RATES={inventario:{base:680,unit:.28,min:950,name:"Inventario físico"},auditoria:{base:1100,unit:.18,min:1400,name:"Auditoría de inventario"},activos:{base:850,unit:.48,min:1200,name:"Activos fijos"},etiquetado:{base:620,unit:.38,min:900,name:"Etiquetado"},digitalizacion:{base:500,unit:.22,min:750,name:"Digitalización"},supervision:{base:900,unit:.12,min:1100,name:"Supervisión operativa"}};
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];let deferred,lastLead;
document.addEventListener("DOMContentLoaded",()=>{$("#year").textContent=new Date().getFullYear();nav();reveal();estimator();forms();cards();pwa();wa();});
function nav(){window.addEventListener("scroll",()=>$("#header").classList.toggle("scrolled",scrollY>20));$("#menuBtn").onclick=()=>$("#mobileNav").classList.toggle("open");$$(".mobile-nav a").forEach(a=>a.onclick=()=>$("#mobileNav").classList.remove("open"))}
function reveal(){const o=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add("visible");o.unobserve(e.target)}}),{threshold:.1});$$(".reveal").forEach(x=>o.observe(x))}
function estimator(){["service","volume","locations","shift","complexity","urgency","equipment","report","travel"].forEach(id=>$("#"+id).addEventListener("input",calc));$("#recalc").onclick=calc;calc()}
function calc(){const k=$("#service").value,r=RATES[k],v=Math.max(1,+$("#volume").value||1),l=Math.max(1,+$("#locations").value||1);let s=r.base+v*r.unit+Math.max(0,l-1)*360;s*=({day:1,night:1.18,mixed:1.12})[$("#shift").value]*({standard:1,medium:1.16,high:1.34})[$("#complexity").value]*({normal:1,soon:1.12,urgent:1.28})[$("#urgency").value];if($("#equipment").checked)s+=Math.max(180,v*.035);if($("#report").checked)s+=280;if($("#travel").checked)s+=950+l*220;s=Math.max(s,r.min);let low=Math.round(s*.92/50)*50,high=Math.round(s*1.14/50)*50;$("#estimateRange").textContent=`${money(low)} – ${money(high)}`;$("#estimateUnit").textContent=`Referencia: ${money((low+high)/2/v)} por unidad · ${l} sede(s)`;return{low,high,service:r.name,volume:v,locations:l}}
function money(v){return new Intl.NumberFormat(CONFIG.locale,{style:"currency",currency:CONFIG.currency,maximumFractionDigits:0}).format(v)}
function forms(){$("#quoteForm").onsubmit=e=>{e.preventDefault();const x=calc(),lead={id:Date.now(),type:"cotizacion",createdAt:new Date().toISOString(),name:$("#leadName").value.trim(),contact:$("#leadContact").value.trim(),service:x.service,volume:x.volume,locations:x.locations,range:`${money(x.low)} – ${money(x.high)}`,shift:$("#shift").selectedOptions[0].text,complexity:$("#complexity").selectedOptions[0].text,urgency:$("#urgency").selectedOptions[0].text};save(lead);showModal(lead)};$("#contactForm").onsubmit=e=>{e.preventDefault();const lead={id:Date.now(),type:"contacto",createdAt:new Date().toISOString(),name:$("#contactName").value.trim(),company:$("#contactCompany").value.trim(),contact:$("#contactData").value.trim(),service:$("#contactService").value,message:$("#contactMessage").value.trim()};save(lead);window.open(`https://wa.me/${CONFIG.whatsapp}?text=${encodeURIComponent(msg(lead))}`,"_blank");toast("Solicitud guardada");e.target.reset()};$$("[data-close]").forEach(x=>x.onclick=()=>$("#modal").classList.remove("open"));$("#downloadBtn").onclick=()=>download(lastLead)}
function save(x){const k="agp_web_leads_v1",a=JSON.parse(localStorage.getItem(k)||"[]");a.unshift(x);localStorage.setItem(k,JSON.stringify(a.slice(0,100)));lastLead=x}
function showModal(x){$("#summary").innerHTML=`<b>${esc(x.name)}</b><br>${esc(x.service)} · ${x.volume.toLocaleString("es-PE")} unidades<br>${x.locations} sede(s) · ${esc(x.range)}`;$("#modalWa").href=`https://wa.me/${CONFIG.whatsapp}?text=${encodeURIComponent(msg(x))}`;$("#modal").classList.add("open")}
function msg(x){return x.type==="cotizacion"?`Hola AGP, deseo una propuesta formal.\n\nNombre/Empresa: ${x.name}\nContacto: ${x.contact}\nServicio: ${x.service}\nVolumen: ${x.volume}\nSedes: ${x.locations}\nHorario: ${x.shift}\nComplejidad: ${x.complexity}\nUrgencia: ${x.urgency}\nRango web: ${x.range}`:`Hola AGP, deseo información.\n\nNombre: ${x.name}\nEmpresa: ${x.company||"-"}\nContacto: ${x.contact}\nServicio: ${x.service}\nDetalle: ${x.message}`}
function cards(){$$(".card button").forEach(b=>b.onclick=()=>{$("#service").value=b.closest(".card").dataset.service;calc();$("#cotizador").scrollIntoView({behavior:"smooth"})})}
function wa(){const h=`https://wa.me/${CONFIG.whatsapp}?text=${encodeURIComponent("Hola AGP, deseo información sobre sus servicios.")}`;$("#waLink").href=h;$("#floatingWa").href=h}
function toast(t){$("#toast").textContent=t;$("#toast").classList.add("show");setTimeout(()=>$("#toast").classList.remove("show"),2500)}
function download(x){const b=new Blob([JSON.stringify(x,null,2)],{type:"application/json"}),u=URL.createObjectURL(b),a=document.createElement("a");a.href=u;a.download=`solicitud-agp-${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(u)}
function pwa(){if("serviceWorker"in navigator)navigator.serviceWorker.register("service-worker.js");window.addEventListener("beforeinstallprompt",e=>{e.preventDefault();deferred=e;$("#installBtn").hidden=false});$("#installBtn").onclick=async()=>{if(!deferred)return;deferred.prompt();await deferred.userChoice;deferred=null;$("#installBtn").hidden=true}}
function esc(v){return String(v).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]))}